name: nextjs
type: "nodejs:20"

hooks:
  build: |
    npm install
    npm run build

  deploy: |
    #!/bin/sh
    set -e

    echo "=== DEPLOY HOOK START ==="  # <-- always logs

    # Log current environment variables
    echo "PLATFORM_BRANCH: $PLATFORM_BRANCH"
    echo "PLATFORM_ENVIRONMENT: $PLATFORM_ENVIRONMENT"
    echo "PLATFORM_PULL_REQUEST: $PLATFORM_PULL_REQUEST"

    if [ -n "$PLATFORM_PULL_REQUEST" ]; then
      echo "PR environment detected – sanitizing database"

      DB_CREDENTIALS=$(echo "$PLATFORM_RELATIONSHIPS" | base64 --decode | jq -r '.database[0]')
      DB_HOST=$(echo "$DB_CREDENTIALS" | jq -r '.host')
      DB_PORT=$(echo "$DB_CREDENTIALS" | jq -r '.port')
      DB_USER=$(echo "$DB_CREDENTIALS" | jq -r '.username')
      DB_PASS=$(echo "$DB_CREDENTIALS" | jq -r '.password')
      DB_NAME=$(echo "$DB_CREDENTIALS" | jq -r '.path')

      echo "Would sanitize database $DB_NAME on $DB_HOST:$DB_PORT"  # safe logging
      # mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" <<EOF
      #   UPDATE users
      #   SET email = CONCAT('user+', id, '@example.com'),
      #       phone = NULL;
      # EOF

      echo "Database sanitization completed"
    else
      echo "Not a PR environment – skipping sanitization"
    fi

    echo "=== DEPLOY HOOK END ==="

web:
  commands:
    start: "npm start"

  locations:
    "/":
      passthru: true

relationships:
  database: "db:mysql"

workers:
  background:
    commands:
      start: "node app/worker.js"

