name: nextjs
type: "nodejs:20"

hooks:
  build: |
    npm install
    npm run build

  deploy: |
    bash .platform/hooks/deploy/sanitize-db.sh

web:
  commands:
    start: "npm start"
  locations:
    "/":
      passthru: true

relationships:
  database: "db:mysql"

workers:
  background:
    commands:
      start: "node app/worker.js"

